AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to launch a Windows EC2 instance in us-east-1 (N.Virginia)

Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable RDP access

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    Description: EC2 instance type
    

Resources:
  MyWindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0159172a5a821bafd   # Replace with latest Windows Server 2022 AMI, AMI ID is different across regions
      KeyName: !Ref KeyPair
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable RDP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0   # Wide open for practice; restrict in real use
